[build]
  command = "npm run build"
  publish = "dist"

# Environment variables should be set in the Netlify UI
# Do not commit sensitive values to this file

[context.production.environment]
  VITE_APP_ENV = "production"

[context.development.environment]
  VITE_APP_ENV = "development"

[context.deploy-preview.environment]
  VITE_APP_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200