import { API_ROUTES } from './constants';

const API_BASE_URL = import.meta.env.VITE_BACKEND_URL;

export const ENDPOINTS = {
  AUTH: {
    GOOGLE: `${API_BASE_URL}${API_ROUTES.AUTH.GOOGLE}`,
    LOGIN: `${API_BASE_URL}${API_ROUTES.AUTH.LOGIN}`,
    LOGOUT: `${API_BASE_URL}${API_ROUTES.AUTH.LOGOUT}`,
    REFRESH: `${API_BASE_URL}${API_ROUTES.AUTH.REFRESH}`
  },
  APPRAISALS: {
    LIST: `${API_BASE_URL}${API_ROUTES.APPRAISALS.LIST}`,
    COMPLETED: `${API_BASE_URL}${API_ROUTES.APPRAISALS.COMPLETED}`,
    DETAILS: (id) => `${API_BASE_URL}${API_ROUTES.APPRAISALS.DETAILS.replace(':id', id)}`,
    DETAILS_EDIT: (id) => `${API_BASE_URL}${API_ROUTES.APPRAISALS.DETAILS_EDIT.replace(':id', id)}`,
    COMPLETE: (id) => `${API_BASE_URL}${API_ROUTES.APPRAISALS.COMPLETE_PROCESS.replace(':id', id)}`,
    SET_VALUE: (id) => `${API_BASE_URL}${API_ROUTES.APPRAISALS.SET_VALUE.replace(':id', id)}`
  }
};